name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emacs-version: [28.2, 29.4, 30.1]
    steps:
      - uses: actions/checkout@v4
      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: emacs-eask/setup-eask@master
        with:
          version: snapshot
      - name: Run tests
        run: |
          # treesit-fold is a dev dependency, but not installable under Emacs
          # 28. I believe Eask will have a nonzero exit code which needs to be
          # caught. Do not enable pipefail in the github actions shell or this
          # solution will break.
          eask install-deps --dev || echo "caught"
          eask test buttercup
